# local에 설치!
version: "3.7"

services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - board-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
      MYSQL_DATABASE: oscboard
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
